/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface UniOcrOptions {
  languages: Array<string>
  confidenceThreshold: number
  timeout: number
}
export interface RecognizeResult {
  text: string
  confidence: string
}
export declare function recognize(
  image: string | Buffer,
  options?: UniOcrOptions | undefined | null,
): Promise<RecognizeResult>
